### ISSUE TITLE
{"message":"not able to send command"}

### ISSUE THREAD

**Issue by xuoguoto** [rtbrick/bngblaster-controller#11]
Hello,
I have been running bngblaster-controller for some time. In last couple of days I am getting this error when I send the command for `session-counters`. The full http transcript is as follows:

```
POST /api/v1/instances/start-single-dualstack-iana-dhcp-iapd-dhcp-ipoe-dhcpv4-nat-qinq-qinq/_command HTTP/1.1
Host: 192.168.200.67:8001
User-Agent: python-requests/2.25.1
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 31
Content-Type: application/json

{"command": "session-counters"}

HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 19 Mar 2024 14:26:08 GMT
Content-Length: 39

{"message":"not able to send command"}
```
There are about 30 tests in my test suite and this error occurs for the same 6 test cases every time. Rest of the test cases run fine. I have run bngblaster as standalone with failing test cases configuration and it works fine without any errors. I have run bngblasterctrl in debug mode with this command `bngblasterctrl -debug -color` but that too do not show any additional errors or warnings. I can reproduce this error reliably every time. Currently I am testing with version 0.0.9 installed using the debs from github.

Any clues to triangulate this error will be much helpful. 

Thanks!

**Comment by GIC-de** [comment]
Which BNG Blaster version is used?

**Comment by xuoguoto** [comment]
> Which BNG Blaster version is used?

`bngblaster-0.8.41-ubuntu-22.04_amd64.deb`

**Comment by GIC-de** [comment]
This means that socket communication between Blaster and Controller failed but I'm actually unable to reproduce this with those version. You can enter the test directory manually and execute the command to see if the issue is here:
```
cd /var/bngblaster/start-single-dualstack-iana-dhcp-iapd-dhcp-ipoe-dhcpv4-nat-qinq-qinq/
sudo bngblaster-cli run.sock session-counters
```

**Comment by xuoguoto** [comment]
In the cases where this error happens the directory listing is as follows:
```
# ls
config.json  run.json  run.log  run.pcap  run.pid  run.s  run.stderr  run.stdout
```
The socket name is just `run.s`. I can use the command given on `run.s` and getting expected output. In the cases where it's working as expected, the name is `run.sock`:
```
# ls
config.json  run.json  run.log  run.pcap  run.pid  run.sock  run.stderr  run.stdout
```

**Comment by GIC-de** [comment]
What is your base operating system (ubuntu 22.04, ...)? 

The file is actually handover as argument `-S run.sock` to the BNG Blaster:

https://github.com/rtbrick/bngblaster-controller/blob/93d699ed16ee03248aa568bb671126d4a0156f48/pkg/controller/repository.go#L225

The BNG Blaster is than using this filename here to open the socket: 

https://github.com/rtbrick/bngblaster/blob/3b9bf5657355f53e6ee0e523a305f736ee3cd658/code/bngblaster/src/bbl_ctrl.c#L510

You should see a log message to verify the path is given correctly. 

https://github.com/rtbrick/bngblaster/blob/3b9bf5657355f53e6ee0e523a305f736ee3cd658/code/bngblaster/src/bbl_ctrl.c#L541C1-L542C1

I never seen such an issue, but may be caused by your long instance name. Maybe you can try with a much shorter instance name:

`start-single-dualstack-iana-dhcp-iapd-dhcp-ipoe-dhcpv4-nat-qinq-qinq`  <<<< maybe to long

**Comment by xuoguoto** [comment]
> What is your base operating system (ubuntu 22.04, ...)?

Yes, Ubuntu 22.04.4 LTS

> `start-single-dualstack-iana-dhcp-iapd-dhcp-ipoe-dhcpv4-nat-qinq-qinq` <<<< maybe to long

Yes, will attempt that and let you know.

**Comment by xuoguoto** [comment]
After reducing the instance name to short string, this issue has not been reproduced so far. I think this ticket can be closed. I will get back if this happens again in future.

Thanks for your support!
